/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.group06.view.container.nhanVien.quanLyHoaDon;

import org.group06.db.DatabaseConstant;
import org.group06.db.dao.DAO_ChiTietHoaDon;
import org.group06.db.dao.DAO_ChiTietPhieuDat;
import org.group06.db.dao.DAO_HoaDon;
import org.group06.db.dao.DAO_PhieuDat;
import org.group06.db.dao.DAO_QuanAo;
import org.group06.model.entity.*;
import org.group06.utils.FontConstant;
import org.group06.utils.FormatCellRenderer;
import org.group06.utils.NumberStandard;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


/**
 * @author Dell
 */
public class WinChiTietDonDatHang extends javax.swing.JFrame {

    private Connection connection = DatabaseConstant.getConnection();
    private DAO_HoaDon dao_HoaDon = new DAO_HoaDon(connection);
    private DAO_ChiTietHoaDon dao_ChiTietHoaDon = new DAO_ChiTietHoaDon(connection);
    private DAO_PhieuDat dao_PhieuDat = new DAO_PhieuDat(connection);
    private DAO_ChiTietPhieuDat dao_ChiTietPhieuDat = new DAO_ChiTietPhieuDat(connection);
    private PhieuDat phieuDat;
    private PanelPhieuTam pnlPhieuTam;
    private KhachHang khachHang;
    private NhanVien nhanVien;
    private KhuyenMai khuyenMai;
    private HashMap<String, String> dsSize = new DAO_QuanAo(connection).getAllKichThuocQA();

    public WinChiTietDonDatHang(PhieuDat phieuDat, PanelPhieuTam pnlPhieuTam) {
        this.phieuDat = phieuDat;
        this.pnlPhieuTam = pnlPhieuTam;
        initComponents();

        if (this.phieuDat.getTrangThai() == PhieuDat.DA_QUA_HAN) {
            btnNhanHang.setEnabled(false);
        } else {
            btnNhanHang.setEnabled(true);
        }
        loadDataTable();
        FormatCellRenderer.formatCellRendererRight(tblDSQuanAo, 3);
        FormatCellRenderer.formatCellRendererRight(tblDSQuanAo, 5);
        FormatCellRenderer.formatCellRendererCenter(tblDSQuanAo, 2);
        FormatCellRenderer.formatCellRendererCenter(tblDSQuanAo, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDSQA = new javax.swing.JPanel();
        srcQuanAo = new javax.swing.JScrollPane();
        tblDSQuanAo = new javax.swing.JTable();
        btnNhanHang = new javax.swing.JButton();
        pnlTTPD = new javax.swing.JPanel();
        lblMaCTPD = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        lblTenCTKM = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        txtMaCTPD = new javax.swing.JTextField();
        lblTongTT = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        txtKH = new javax.swing.JTextField();
        txtNV = new javax.swing.JTextField();
        txtTenCTKM = new javax.swing.JTextField();
        txtTongTT = new javax.swing.JTextField();
        lblNgayNhan = new javax.swing.JLabel();
        txtNgayNhan = new javax.swing.JTextField();
        lblTitleCTPD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDSQA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách quần áo đã đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        tblDSQuanAo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblDSQuanAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã quần áo", "Tên quần áo", "Size", "Giá tiền", "Số lượng", "Thành tiền", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSQuanAo.setRowHeight(30);
        tblDSQuanAo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSQuanAoMouseClicked(evt);
            }
        });
        srcQuanAo.setViewportView(tblDSQuanAo);
        if (tblDSQuanAo.getColumnModel().getColumnCount() > 0) {
            tblDSQuanAo.getColumnModel().getColumn(0).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(1).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(2).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(3).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(4).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(5).setResizable(false);
            tblDSQuanAo.getColumnModel().getColumn(6).setResizable(false);
        }

        btnNhanHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhanHang.setText("Nhận Hàng");
        btnNhanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDSQALayout = new javax.swing.GroupLayout(pnlDSQA);
        pnlDSQA.setLayout(pnlDSQALayout);
        pnlDSQALayout.setHorizontalGroup(
            pnlDSQALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(srcQuanAo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSQALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDSQALayout.setVerticalGroup(
            pnlDSQALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSQALayout.createSequentialGroup()
                .addComponent(srcQuanAo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        lblMaCTPD.setFont(FontConstant.FONT_LABEL);
        lblMaCTPD.setText("Mã chi tiết phiếu đặt:");

        lblTenKH.setFont(FontConstant.FONT_LABEL);
        lblTenKH.setText("Tên khách hàng:");

        lblTenCTKM.setFont(FontConstant.FONT_LABEL);
        lblTenCTKM.setText("Tên chương trình KM (Nếu có):");

        lblNgayTao.setFont(FontConstant.FONT_LABEL);
        lblNgayTao.setText("Ngày tạo phiếu đặt:");

        lblTenNV.setFont(FontConstant.FONT_LABEL);
        lblTenNV.setText("Nhân viên lập phiếu đặt:");

        txtMaCTPD.setBackground(new java.awt.Color(242, 242, 242));
        txtMaCTPD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaCTPD.setText(phieuDat.getMaPhieuDat());
        txtMaCTPD.setBorder(null);
        txtMaCTPD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaCTPD.setEnabled(false);
        txtMaCTPD.setPreferredSize(new java.awt.Dimension(71, 30));

        lblTongTT.setFont(FontConstant.FONT_LABEL);
        lblTongTT.setText("Tổng thành tiền phải trả:");

        txtNgayTao.setBackground(new java.awt.Color(242, 242, 242));
        txtNgayTao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgayTao.setBorder(null);
        txtNgayTao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNgayTao.setEnabled(false);
        txtNgayTao.setPreferredSize(new java.awt.Dimension(71, 30));

        txtKH.setBackground(new java.awt.Color(242, 242, 242));
        txtKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKH.setText(phieuDat.getKhachHang().getTenKH());
        txtKH.setBorder(null);
        txtKH.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtKH.setEnabled(false);
        txtKH.setPreferredSize(new java.awt.Dimension(71, 30));

        txtNV.setBackground(new java.awt.Color(242, 242, 242));
        txtNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNV.setText(phieuDat.getNhanVien().getTenNV());
        txtNV.setBorder(null);
        txtNV.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNV.setEnabled(false);
        txtNV.setPreferredSize(new java.awt.Dimension(71, 30));

        txtTenCTKM.setBackground(new java.awt.Color(242, 242, 242));
        txtTenCTKM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenCTKM.setText(phieuDat.getKhuyenMai() != null ? phieuDat.getKhuyenMai().getTenCTKM() + " (" + NumberStandard.formatPercent(phieuDat.getKhuyenMai().getMucGiamGia()) + ")" : "");
        txtTenCTKM.setBorder(null);
        txtTenCTKM.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenCTKM.setEnabled(false);
        txtTenCTKM.setPreferredSize(new java.awt.Dimension(71, 30));

        txtTongTT.setBackground(new java.awt.Color(242, 242, 242));
        txtTongTT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTongTT.setBorder(null);
        txtTongTT.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtTongTT.setEnabled(false);
        txtTongTT.setPreferredSize(new java.awt.Dimension(71, 30));

        lblNgayNhan.setFont(FontConstant.FONT_LABEL);
        lblNgayNhan.setText("Ngày lấy quần áo:");

        txtNgayNhan.setBackground(new java.awt.Color(242, 242, 242));
        txtNgayNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgayNhan.setBorder(null);
        txtNgayNhan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNgayNhan.setEnabled(false);
        txtNgayNhan.setPreferredSize(new java.awt.Dimension(71, 30));

        javax.swing.GroupLayout pnlTTPDLayout = new javax.swing.GroupLayout(pnlTTPD);
        pnlTTPD.setLayout(pnlTTPDLayout);
        pnlTTPDLayout.setHorizontalGroup(
            pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTPDLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenCTKM, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgayNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaCTPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTongTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNV, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addComponent(txtTenCTKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTongTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaCTPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        pnlTTPDLayout.setVerticalGroup(
            pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTPDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaCTPD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaCTPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTPDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        // Chuyển đổi thành chuỗi
        String dateString = dateFormat.format(phieuDat.getNgayTao());
        txtNgayTao.setText(dateString);
        SimpleDateFormat dateFormatNhan = new SimpleDateFormat("dd/MM/yyyy");
        // Chuyển đổi thành chuỗi
        String dateStringNhan = dateFormatNhan.format(phieuDat.getNgayNhan());
        txtNgayNhan.setText(dateStringNhan);

        lblTitleCTPD.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitleCTPD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCTPD.setText("Chi Tiết Phiếu Đặt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDSQA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTTPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleCTPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitleCTPD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTTPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDSQA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanHangActionPerformed
        ArrayList<ChiTietPhieuDat> dsCTPD = dao_ChiTietPhieuDat.getAllByID(phieuDat.getMaPhieuDat());
        String maHoaDon = taoMaPD();
        Date ngayHienTai = new Date(System.currentTimeMillis());

        khachHang = phieuDat.getKhachHang();
        nhanVien = phieuDat.getNhanVien();
        khuyenMai = phieuDat.getKhuyenMai();

        btnNhanHang.setEnabled(true);
        HoaDon hoaDonBanHang = new HoaDon(maHoaDon, ngayHienTai, khachHang, nhanVien, khuyenMai);
        int selection = JOptionPane.showConfirmDialog(this, "Bạn có muốn xác nhận nhận hàng không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selection == JOptionPane.YES_OPTION) {
            if (dao_HoaDon.add(hoaDonBanHang)) {
                for (ChiTietPhieuDat phieuDat : dsCTPD) {
                    ChiTietHoaDon cthd = new ChiTietHoaDon(hoaDonBanHang, phieuDat.getQuanAo(), phieuDat.getSoLuong(), phieuDat.getGiaBan(), phieuDat.getLoiNhuan());
                    dao_ChiTietHoaDon.add(cthd);
                }
            }
            JOptionPane.showMessageDialog(this, "Đã lưu hóa đơn");

            dao_PhieuDat.delete(phieuDat.getMaPhieuDat());
            pnlPhieuTam.loadDataTable();
            this.dispose();
        }
    }//GEN-LAST:event_btnNhanHangActionPerformed

    private void tblDSQuanAoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSQuanAoMouseClicked
        if (evt.getClickCount() == 2) {
            callFrameWinTraPhieuDatHang();
        }
    }//GEN-LAST:event_tblDSQuanAoMouseClicked

    private void callFrameWinTraPhieuDatHang() {
        WinTraPhieuDatHang frTPDH = new WinTraPhieuDatHang(this.getSelectedWinTraPhieuDatHang(), this, this.pnlPhieuTam);
        frTPDH.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frTPDH.setResizable(false);
        frTPDH.setVisible(true);
    }

    private ChiTietPhieuDat getSelectedWinTraPhieuDatHang() {
        String mQA = tblDSQuanAo.getValueAt(tblDSQuanAo.getSelectedRow(), 0).toString();

        if (tblDSQuanAo.getSelectedRow() == -1) {
            return null;
        } else {
            return dao_ChiTietPhieuDat.getQA(mQA);
        }
    }

    public int getSoLuongDaDat() {
        if (tblDSQuanAo.getSelectedRow() == -1) {
            return -1;
        } else {
            int sl = (int) tblDSQuanAo.getValueAt(tblDSQuanAo.getSelectedRow(), 4);
            return sl;
        }
    }
    
    public int getTrangThaiThanhToan() {
        int temp = pnlPhieuTam.getTrangThai();
        return temp;
    }
    
    public String taoMaPD() {
        int count = dao_PhieuDat.loadMaPDCount();
        count++;
        // Tạo mã phiếu đặt theo quy tắc và có thứ tự
        return "PD" + String.format("%03d", count); // Ví dụ: PD001, PD002,...
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhanHang;
    private javax.swing.JLabel lblMaCTPD;
    private javax.swing.JLabel lblNgayNhan;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblTenCTKM;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTitleCTPD;
    private javax.swing.JLabel lblTongTT;
    private javax.swing.JPanel pnlDSQA;
    private javax.swing.JPanel pnlTTPD;
    private javax.swing.JScrollPane srcQuanAo;
    private javax.swing.JTable tblDSQuanAo;
    private javax.swing.JTextField txtKH;
    private javax.swing.JTextField txtMaCTPD;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTenCTKM;
    private javax.swing.JTextField txtTongTT;
    // End of variables declaration//GEN-END:variables

    public void loadDataTable() {
        double tinhTongThanhTien = 0, mucGiamGia = 0;
        String pd = phieuDat.getMaPhieuDat().toString();
        ArrayList<ChiTietPhieuDat> dsCTPD = dao_ChiTietPhieuDat.getAllByID(pd);
        DefaultTableModel modelCTPD = (DefaultTableModel) this.tblDSQuanAo.getModel();
        modelCTPD.setRowCount(0);
        for (ChiTietPhieuDat ctpd : dsCTPD) {
            String maQA = ctpd.getQuanAo().getMaQA();
            String tenQA = ctpd.getQuanAo().getTenQA();
            String giaBan = NumberStandard.formatMoney(ctpd.getGiaBan());
            int soLuong = ctpd.getSoLuong();
            String thanhTien = NumberStandard.formatMoney(ctpd.getGiaBan() * soLuong);

            tinhTongThanhTien += ctpd.getGiaBan() * soLuong;
            
            // lấy tên kích thước từ mã kích kích thước có sẵn
            String size = "";
            for (Map.Entry<String, String> item : dsSize.entrySet()) {
                if(item.getKey().equals(ctpd.getQuanAo().getMaKichThuoc())) {
                    size = item.getValue();
                    break;
                }
            }
            
            String gc = ctpd.getGhiChu();
            
            Object[] data = {maQA, tenQA, size, giaBan, soLuong, thanhTien, gc};
            modelCTPD.addRow(data);

            if (ctpd.getPhieuDat().getKhuyenMai() != null) {
                mucGiamGia = (ctpd.getPhieuDat().getKhuyenMai().getMucGiamGia()) / 100;
            }
        }
        double tongTienSauVAT = tinhTongThanhTien * 1.08;
        double ttt = (tongTienSauVAT * (1.0f - mucGiamGia));
        String tongThanhTien = NumberStandard.formatMoney(ttt);
        txtTongTT.setText(tongThanhTien);
    }
}
