/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.group06.view.components.search;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author Le Minh Bao
 */
public class PanelSearch extends javax.swing.JPanel {

    private SearchClickEvent event;
    
    /**
     * Creates new form PanelSearch
     */
    public PanelSearch() {
        initComponents();
    }

    public void setData(ArrayList<Data> datas) {
        this.removeAll();
        for (Data data : datas) {
            SearchItem searchItem = new SearchItem(data);
            
            searchItem.addEvent(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    event.itemClick(data);
                }
            });
            
            add(searchItem);

        }
        repaint();
        revalidate();
    }

    public int getItemSize() {
        return getComponentCount();
    }

    public void addEventClick(SearchClickEvent event) {
        this.event = event;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.white);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
