/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.group06.view.container.nhanVien.thongKe;

/**
 *
 * @author Le Minh Bao
 */
public class PanelThongKeQuanAo extends javax.swing.JPanel {

    /**
     * Creates new form PanelThongKeQuanAo
     */
    public PanelThongKeQuanAo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        tabLuaChonHienThi = new javax.swing.JTabbedPane();
        tabDanhSachChiTiet = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tabHienThiBieuDo = new javax.swing.JTabbedPane();
        pnlBieuDoTheoNgay = new javax.swing.JPanel();
        pnlBieuDoTheoThang = new javax.swing.JPanel();
        pnlBieuDoTheoNam = new javax.swing.JPanel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thống Kê Quần Áo");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout tabDanhSachChiTietLayout = new javax.swing.GroupLayout(tabDanhSachChiTiet);
        tabDanhSachChiTiet.setLayout(tabDanhSachChiTietLayout);
        tabDanhSachChiTietLayout.setHorizontalGroup(
            tabDanhSachChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDanhSachChiTietLayout.createSequentialGroup()
                .addGroup(tabDanhSachChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 862, Short.MAX_VALUE))
        );
        tabDanhSachChiTietLayout.setVerticalGroup(
            tabDanhSachChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDanhSachChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        tabLuaChonHienThi.addTab("Danh Sách Chi Tiết", tabDanhSachChiTiet);

        javax.swing.GroupLayout pnlBieuDoTheoNgayLayout = new javax.swing.GroupLayout(pnlBieuDoTheoNgay);
        pnlBieuDoTheoNgay.setLayout(pnlBieuDoTheoNgayLayout);
        pnlBieuDoTheoNgayLayout.setHorizontalGroup(
            pnlBieuDoTheoNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        pnlBieuDoTheoNgayLayout.setVerticalGroup(
            pnlBieuDoTheoNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        tabHienThiBieuDo.addTab("Biểu Đồ Theo Ngày", pnlBieuDoTheoNgay);

        javax.swing.GroupLayout pnlBieuDoTheoThangLayout = new javax.swing.GroupLayout(pnlBieuDoTheoThang);
        pnlBieuDoTheoThang.setLayout(pnlBieuDoTheoThangLayout);
        pnlBieuDoTheoThangLayout.setHorizontalGroup(
            pnlBieuDoTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        pnlBieuDoTheoThangLayout.setVerticalGroup(
            pnlBieuDoTheoThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        tabHienThiBieuDo.addTab("Biều Đồ Theo Tháng", pnlBieuDoTheoThang);

        javax.swing.GroupLayout pnlBieuDoTheoNamLayout = new javax.swing.GroupLayout(pnlBieuDoTheoNam);
        pnlBieuDoTheoNam.setLayout(pnlBieuDoTheoNamLayout);
        pnlBieuDoTheoNamLayout.setHorizontalGroup(
            pnlBieuDoTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        pnlBieuDoTheoNamLayout.setVerticalGroup(
            pnlBieuDoTheoNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        tabHienThiBieuDo.addTab("Biểu Đồ Theo Năm", pnlBieuDoTheoNam);

        tabLuaChonHienThi.addTab("Biểu Đồ Trực Quan", tabHienThiBieuDo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabLuaChonHienThi)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabLuaChonHienThi)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBieuDoTheoNam;
    private javax.swing.JPanel pnlBieuDoTheoNgay;
    private javax.swing.JPanel pnlBieuDoTheoThang;
    private javax.swing.JPanel tabDanhSachChiTiet;
    private javax.swing.JTabbedPane tabHienThiBieuDo;
    private javax.swing.JTabbedPane tabLuaChonHienThi;
    // End of variables declaration//GEN-END:variables
}
