/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.group06.view.container.nhanVien;

import org.group06.model.entity.NhanVien;
import org.group06.utils.ImagePath;
import org.group06.view.components.panels.ImagePanel;
import org.group06.view.components.tabbedPane.ButtonAddTabComponent;
import org.group06.view.components.tabbedPane.ButtonTabComponent;
import org.group06.view.components.tabbedPane.TabBanHang_DatHang;

import javax.swing.*;

/**
 * @author Le Minh Bao
 */
public class PanelBanHang_DatHang extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PanelBanHang_DatHang(NhanVien nv) {
        tab = new JTabbedPane();

        // add tab change listener
        tab.addChangeListener(e -> {
            int i = tab.getSelectedIndex();
            if (tab.getComponentAt(i) instanceof TabBanHang_DatHang tabBanHangDatHang) {
                tabBanHangDatHang.synchronizeData();
            }
        });

        initComponents();
        tab.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        tab.addTab("Đơn hàng mới 1", new TabBanHang_DatHang(nv, tab));
        tab.setTabComponentAt(0, new ButtonTabComponent(tab));
        tab.setSelectedIndex(0);
        // add ButtonAddTabComponent to add new tab
        tab.addTab("", new ImagePanel(ImagePath.THUMBNAIL_MAIN, 1920, 1080));
        // block this tab be selected
        tab.setEnabledAt(1, false);
        tab.setTabComponentAt(1, new ButtonAddTabComponent(tab, nv));
    }

    public PanelBanHang_DatHang(NhanVien nv, JTabbedPane tab) {
        this.tab = tab;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getTab() {
        return tab;
    }
}
