/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.group06.view.components.panels.container;

import org.group06.utils.ColorConstant;
import org.group06.utils.FontConstant;
import org.group06.utils.ImagePath;
import org.group06.view.components.panels.ImagePanel;

/**
 * @author lemin
 */
public class PanelQuanAoNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanAo
     */
    public PanelQuanAoNhanVien() {
        initComponents();
        tblSize.getTableHeader().setBackground(ColorConstant.BACKGROUND_SIDEBAR);
        tblSize.getTableHeader().setForeground(ColorConstant.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDetail = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        txtTen = new org.group06.view.components.textFields.TextField()
        ;
        lblKieu = new javax.swing.JLabel();
        txtKieu = new org.group06.view.components.textFields.TextField()
        ;
        lblGia = new javax.swing.JLabel();
        txtGia = new org.group06.view.components.textFields.TextField()
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSize = new javax.swing.JTable();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnImg = new ImagePanel(ImagePath.PRODUCT_EXAMPLE, 380, 380);
        pnListProduct = new javax.swing.JPanel();
        lblTitleSanPham = new javax.swing.JLabel();
        txtTimMaQA = new org.group06.view.components.textFields.TextField("Mã Quần Áo", ColorConstant.BLACK);
        btnTimMaQA = new org.group06.view.components.buttons.StaticRoundButton("", ImagePath.ICON_SEARCH, ColorConstant.BUTTON_LOGIN_NORMAL, ColorConstant.BUTTON_LOGIN_HOVER, ColorConstant.BUTTON_LOGIN_CLICK);
        scrQuanAo = new javax.swing.JScrollPane();
        tblQuanAo = new javax.swing.JTable();

        setBackground(ColorConstant.BACKGROUND_CONTAINER);

        pnDetail.setBackground(org.group06.utils.ColorConstant.DETAIL_PRODUCT_BACKGROUND);
        pnDetail.setPreferredSize(new java.awt.Dimension(400, 400));

        lblTen.setFont(FontConstant.FONT_LABEL);
        lblTen.setText("Tên:");

        txtTen.setFont(FontConstant.FONT_TEXT);
        txtTen.setText("Đầm dạ hội");
        txtTen.setDisabledTextColor(ColorConstant.BLACK);
        txtTen.setEnabled(false);

        lblKieu.setFont(FontConstant.FONT_LABEL);
        lblKieu.setText("Kiểu:");

        txtKieu.setFont(FontConstant.FONT_TEXT);
        txtKieu.setText("Đầm");
        txtKieu.setDisabledTextColor(ColorConstant.BLACK);
        txtKieu.setEnabled(false);

        lblGia.setFont(FontConstant.FONT_LABEL);
        lblGia.setText("Giá:");

        txtGia.setFont(FontConstant.FONT_TEXT);
        txtGia.setText("125,000 vnđ");
        txtGia.setDisabledTextColor(ColorConstant.BLACK);
        txtGia.setEnabled(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(395, 159));

        tblSize.setBackground(ColorConstant.BUTTON_HOVER);
        tblSize.setFont(FontConstant.FONT_TEXT);
        tblSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S",  new Integer(20)},
                {"M",  new Integer(10)},
                {"L",  new Integer(30)},
                {"XL",  new Integer(60)},
                {"XXL",  new Integer(10)},
                {"XXXL",  new Integer(10)}
            },
            new String [] {
                "Kích Thước", "Số Lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSize.setEnabled(false);
        tblSize.setGridColor(new java.awt.Color(153, 153, 153));
        tblSize.setRowHeight(40);
        tblSize.setShowGrid(true);
        jScrollPane1.setViewportView(tblSize);
        if (tblSize.getColumnModel().getColumnCount() > 0) {
            tblSize.getColumnModel().getColumn(0).setResizable(false);
            tblSize.getColumnModel().getColumn(1).setResizable(false);
        }

        lblMoTa.setFont(FontConstant.FONT_LABEL);
        lblMoTa.setText("Mô tả:");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(ColorConstant.BUTTON_HOVER);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(FontConstant.FONT_TEXT);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        pnImg.setPreferredSize(new java.awt.Dimension(380, 380));
        pnImg.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnImgLayout = new javax.swing.GroupLayout(pnImg);
        pnImg.setLayout(pnImgLayout);
        pnImgLayout.setHorizontalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        pnImgLayout.setVerticalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailLayout.createSequentialGroup()
                                .addComponent(lblTen)
                                .addGap(31, 31, 31))
                            .addGroup(pnDetailLayout.createSequentialGroup()
                                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKieu)
                                    .addComponent(lblGia))
                                .addGap(27, 27, 27)))
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtTen)
                            .addComponent(txtKieu)
                            .addComponent(txtGia)))
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(lblMoTa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKieu)
                    .addComponent(txtKieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGia)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMoTa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnListProduct.setBackground(ColorConstant.BACKGROUND_CONTAINER);

        lblTitleSanPham.setFont(org.group06.utils.FontConstant.FONT_HEADER);
        lblTitleSanPham.setForeground(org.group06.utils.ColorConstant.WHITE);
        lblTitleSanPham.setText("Danh Sách Quần Áo");

        txtTimMaQA.setFont(FontConstant.FONT_TEXT);
        txtTimMaQA.setToolTipText("Nhập mã quần áo cần tìm");
        txtTimMaQA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimMaQAActionPerformed(evt);
            }
        });

        btnTimMaQA.setToolTipText("Click để tìm kiếm khách hàng");
        btnTimMaQA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimMaQA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        scrQuanAo.setBorder(null);
        scrQuanAo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrQuanAo.setFont(org.group06.utils.FontConstant.FONT_LABEL);

        tblQuanAo.setAutoCreateRowSorter(true);
        tblQuanAo.setBackground(org.group06.utils.ColorConstant.BACKGROUND_NORMAL);
        tblQuanAo.setFont(org.group06.utils.FontConstant.FONT_TEXT);
        tblQuanAo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"QA001", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA002", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA003", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA004", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA005", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA006", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA007", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA008", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA009", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA010", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA011", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA012", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA013", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA014", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA015", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA016", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA017", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA018", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA019", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA020", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA021", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA022", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA023", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA024", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA025", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA026", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA027", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA028", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA01", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"},
                {"QA01", "Đầm dạ hội",  new Double(80000.0),  new Double(125000.0),  new Double(0.0), "Còn Hàng"}
            },
            new String [] {
                "Mã", "Tên", "Giá Nhập", "Lợi Nhuận", "Khuyến Mãi", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblQuanAo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblQuanAo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblQuanAo.setFillsViewportHeight(true);
        tblQuanAo.setGridColor(org.group06.utils.ColorConstant.BLACK);
        tblQuanAo.setRowHeight(50);
        tblQuanAo.setSelectionBackground(org.group06.utils.ColorConstant.BACKGROUND_SIDEBAR);
        tblQuanAo.setSelectionForeground(org.group06.utils.ColorConstant.WHITE);
        tblQuanAo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQuanAo.setShowGrid(true);
        tblQuanAo.getTableHeader().setResizingAllowed(false);
        tblQuanAo.getTableHeader().setReorderingAllowed(false);
        scrQuanAo.setViewportView(tblQuanAo);

        javax.swing.GroupLayout pnListProductLayout = new javax.swing.GroupLayout(pnListProduct);
        pnListProduct.setLayout(pnListProductLayout);
        pnListProductLayout.setHorizontalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListProductLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnListProductLayout.createSequentialGroup()
                        .addComponent(lblTitleSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimMaQA, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimMaQA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(scrQuanAo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        pnListProductLayout.setVerticalGroup(
            pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListProductLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimMaQA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimMaQA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitleSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrQuanAo)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnListProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnListProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimMaQAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimMaQAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimMaQAActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimMaQA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblKieu;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTitleSanPham;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pnImg;
    private javax.swing.JPanel pnListProduct;
    private javax.swing.JScrollPane scrQuanAo;
    private javax.swing.JTable tblQuanAo;
    private javax.swing.JTable tblSize;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKieu;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimMaQA;
    // End of variables declaration//GEN-END:variables
}
